// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { context } from './helmetContext';
import { HelmetProvider } from 'E:/easten/dev/web/easten-lib/node_modules/@umijs/renderer-react';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
};
