// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/easten/dev/web/easten-lib/node_modules/dumi/theme-default/slots/NotFound/index.js';
