// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
// plugins
export { getSketchJSON } from 'E:/easten/dev/web/easten-lib/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export {
  Helmet,
  HelmetProvider,
  Link,
  NavLink,
  Navigate,
  Outlet,
  __getRoot,
  __useFetcher,
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
} from 'E:/easten/dev/web/easten-lib/node_modules/@umijs/renderer-react';
export type { History } from 'E:/easten/dev/web/easten-lib/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { createHistory, history } from './core/history';
export { terminal } from './core/terminal';
export {
  ApplyPluginsType,
  PluginManager,
} from 'E:/easten/dev/web/easten-lib/node_modules/umi/client/client/plugin.js';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
