// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useSiteData } from 'dumi';
import { useLayoutEffect, type FC } from 'react';
import './nprogress.css';
import nprogress from 'E:/easten/dev/web/easten-lib/node_modules/nprogress';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    };
  }, []);

  return null;
};

export default DumiLoading;
