name: Build and Deploy Documentation

on:
  push:
    branches:
      - doc  # Or the branch of your choice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # You can specify the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run docs:build
      run: npm run docs:build

    # Add additional steps here to deploy your documentation
    # For example, if you are deploying to GitHub Pages:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc  # Set the path to your build documents
